import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {TextDivisor} from '@/modules/textDivisor'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mateus' Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.menuHorizontal}>
          <div className={styles.conteudo_menuHorizontal}>
            <h4>Mateus' Portfolio</h4>
            <div className={styles.rotas_menuHorizontal}>
              <a href=""><p>Sobre</p></a>
              <a href=""><p>Repositórios</p></a>
              <a href=""><p>Contato</p></a>
            </div>
          </div>
        </div>
        <div className={styles.container}>
          <div className={styles.initialSection}>
            <div className={styles.textos_initialSection}>
              <h1>Hello, World!</h1>
              <TextDivisor largura={120} />
              <h5>Amo Programação,<br />Academia e Pizza </h5>
            </div>
            <div className={styles.ilustracao_initialSection}>
              <Image src={require('@/assets/ilustrations/ilustration_computerGuy.png')} alt='Homem com headset usando um computador' />
            </div>
          </div>
          <div className={styles.sobreSection}>

          </div>
          <div className={styles.repositoriosSection}>

          </div>
          <div className={styles.contatoSection}>

          </div>
        </div>
      </main>
    </>
  )
}
